# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
#
# https://puppet.com/docs/pe/latest/overview/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/latest/overview/getting_support_for_pe.html
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# PE 2016.4.15  4.10.12  2.1.9  2018-12 (LTS)
# SIMP 6.0      4.8.2    2.1.9  TBD
# SIMP 6.1      4.10.6   2.1.9  TBD
# SIMP 6.2      4.10.12  2.1.9  TBD
# SIMP 6.3      5.5.7    2.4.4  TBD***
# PE 2018.1     5.5.6    2.4.4  2020-05 (LTS)***
#
# *** = Modules created for SIMP 6.3+ are not required to support Puppet < 5.5
---
.cache_bundler: &cache_bundler
  cache:
    untracked: true
    # A broad attempt at caching between runs (ala Travis CI)
    key: "${CI_PROJECT_NAMESPACE}__bundler"
    paths:
      - '.vendor'
      - 'vendor'

.setup_bundler_env: &setup_bundler_env
  before_script:
    - 'echo Files in cache: $(find .vendor | wc -l) || :'
    - 'export GEM_HOME=.vendor/gem_install'
    - 'export BUNDLE_CACHE_PATH=.vendor/bundler'
    - 'declare GEM_BUNDLER_VER=(-v ''~> ${BUNDLER_VERSION:-1.16.0}'')'
    - declare GEM_INSTALL=(gem install --no-document)
    - declare BUNDLER_INSTALL=(bundle install --no-binstubs --jobs $(nproc) --path=.vendor "${FLAGS[@]}")
    - gem list -ie "${GEM_BUNDLE_VER[@]}" --silent bundler || "${GEM_INSTALL[@]}" --local "${GEM_BUNDLE_VER[@]}" bundler || "${GEM_INSTALL[@]}" "${GEM_BUNDLE_VER[@]}" bundler
    - 'rm -rf pkg/ || :'
    - bundle check || rm -f Gemfile.lock && ("${BUNDLER_INSTALL[@]}" --local || "${BUNDLER_INSTALL[@]}")


.validation_checks: &validation_checks
  script:
    - bundle exec rake syntax
    - bundle exec rake check:dot_underscore
    - bundle exec rake check:test_file
    - bundle exec rake pkg:check_version
    - bundle exec rake pkg:compare_latest_tag
    - bundle exec rake lint
    - bundle exec rake clean
    - bundle exec puppet module build

.spec_tests: &spec_tests
  script:
    - bundle exec rake spec

# To avoid running a prohibitive number of tests every commit,
# don't set this env var in your gitlab instance
.only_with_SIMP_FULL_MATRIX: &only_with_SIMP_FULL_MATRIX
  only:
    variables:
      - $SIMP_FULL_MATRIX

stages:
  - validation
  - unit
  - acceptance
  - deploy

# Puppet 4.10 for PE 2016.4.15  support (EOL:2018-12)
# See: https://puppet.com/misc/puppet-enterprise-lifecycle
# --------------------------------------
pup4_10-validation:
  stage: validation
  tags:
    - docker
  image: ruby:2.1
  variables:
    PUPPET_VERSION: '~> 4.10.0'
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *validation_checks

pup4_10-unit:
  stage: unit
  tags:
    - docker
  image: ruby:2.1
  variables:
    PUPPET_VERSION: '~> 4.10.0'
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *spec_tests


# Puppet 5.3 for PE 2017.3 support (EOL: 2018-07)
# Puppet 5.5.6 for PE 2018.1 support (EOL:2020-05)
# See: https://puppet.com/misc/puppet-enterprise-lifecycle
# --------------------------------------
pup5_5_6-validation:
  stage: validation
  tags:
    - docker
  image: ruby:2.4
  variables:
    PUPPET_VERSION: '5.5.6'
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *validation_checks

pup5_5_6-unit:
  stage: unit
  tags:
    - docker
  image: ruby:2.4
  variables:
    PUPPET_VERSION: '5.5.6'
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *spec_tests


# Keep an eye on the latest puppet 5
# ----------------------------------
pup5_latest-validation:
  stage: validation
  tags:
    - docker
  image: ruby:2.4
  variables:
    PUPPET_VERSION: '~> 5.0'
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *validation_checks

pup5_latest-unit:
  stage: unit
  tags:
    - docker
  image: ruby:2.4
  variables:
    PUPPET_VERSION: '~> 5.0'
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *spec_tests


# Acceptance tests
# ==============================================================================
default:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '~> 4.10.4'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[default]

default-puppet5:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '~> 5.5'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[default]

default-puppet5-fips:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '~> 5.5'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    BEAKER_fips: 'yes'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[default]

default-oel:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *only_with_SIMP_FULL_MATRIX
  variables:
    PUPPET_VERSION: '~> 4.10.4'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[default,oel]

default-oel-puppet5:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '~> 5.5'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[default,oel]

default-oel-puppet5-fips:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *only_with_SIMP_FULL_MATRIX
  variables:
    PUPPET_VERSION: '~> 5.5'
    BEAKER_PUPPET_COLLECTION: 'puppet5'
    BEAKER_fips: 'yes'
  script:
    - bundle exec rake spec_clean
    - bundle exec rake beaker:suites[default,oel]
